### ISSUE TITLE
Add printed parts and dxf for lasercut acrylic

### ISSUE THREAD

**Issue by HiddenTr0ll** [makermoekoe/Reflow-Controller#10]
Hello @makermoekoe , 
I am building your wonderful controller at the moment and noticed, that you haven't uploaded the 3D-Printed files or the file to lasercut the transparent acrylic sheet. 

These would help me out tremendously, as I have the exact same LIDL oven as you do.

Many thanks in advance!

**Comment by makermoekoe** [comment]
Sorry for the late response! I have just added all the 3D models
